POST http://localhost:3000/productos
Content-Type: application/json

{
  "nombre": "Zapatpos Rojos",
  "codigo": "08",
  "precio": 2000,
  "cantidad": 12,
  "categoria": "Calzado"
}

###

GET http://localhost:3000/productos
Accept: application/json