POST http://localhost:3000/productos
Content-Type: application/json

{
  "nombre": "Mono Robot",
  "precio": 2000,
  "cantidad": 12,
  "categoria": "Calzado"
}

###

GET http://localhost:3000/productos
Accept: application/json

### 
DELETE http://localhost:3000/productos/39
Accept: application/json

### 
GET http://localhost:3000/productos/42
Accept: application/json


###
PUT http://localhost:3000/productos/35
Content-Type: application/json

{
  "nombre": "Queso azul con moho",
  "precio": 55,
  "cantidad": 32,
  "categoria": "Comida"
}
